Repository ssg-240304-java2/wms-InfinityIterators, pull requests merged in 2024-05, with the labels that each got.

#25 새로운 유틸리티 클래스 추가: Input, Console, MyBatisTemplate, Menu
  docs/utils/interaction/Console.md
  docs/utils/interaction/DisplayType.md
  docs/utils/interaction/Input.md
  src/main/java/com/infinityiterators/bookwms/utils/database/MyBatisTemplate.java
  src/main/java/com/infinityiterators/bookwms/utils/interaction/Console.java
  src/main/java/com/infinityiterators/bookwms/utils/interaction/DisplayType.java
  src/main/java/com/infinityiterators/bookwms/utils/interaction/Input.java
  src/main/java/com/infinityiterators/bookwms/utils/interaction/Menu.java
  src/main/resources/asciilogo.txt
  src/main/resources/config/mybatis-config.xml
Labels: Feature, Utils

#36 Add Order Management Feature and Update MyBatis Configuration
  src/main/java/com/infinityiterators/bookwms/order/controller/OrderController.java
  src/main/java/com/infinityiterators/bookwms/order/dao/OrderDAO.java
  src/main/java/com/infinityiterators/bookwms/order/dto/CartDTO.java
  src/main/java/com/infinityiterators/bookwms/order/dto/CartItemDTO.java
  src/main/java/com/infinityiterators/bookwms/order/dto/OrderDTO.java
  src/main/java/com/infinityiterators/bookwms/order/dto/OrderItemDTO.java
  src/main/java/com/infinityiterators/bookwms/order/mapper/OrderMapper.java
  src/main/java/com/infinityiterators/bookwms/order/model/Cart.java
  src/main/java/com/infinityiterators/bookwms/order/model/CartItem.java
  src/main/java/com/infinityiterators/bookwms/order/model/service/OrderService.java
  src/main/java/com/infinityiterators/bookwms/order/view/OrderMainMenu.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/order/mapper/OrderMapper.xml
Labels: enhancement, good first issue, Feature, Priority: High

#35 고객 관리 관련 기능 추가 및 코드 연결
  src/main/java/com/infinityiterators/bookwms/EntryPoint.java
  src/main/java/com/infinityiterators/bookwms/view/AdminMenu.java
  src/main/java/com/infinityiterators/bookwms/view/CustomerLoginMenu.java
  src/main/java/com/infinityiterators/bookwms/view/CustomerMenu.java
  src/main/java/com/infinityiterators/bookwms/view/MainMenu.java
Labels: menu

#39 Order 관련 성공,실패 상세 메시지 출력 기능
  src/main/java/com/infinityiterators/bookwms/order/controller/OrderController.java
  src/main/java/com/infinityiterators/bookwms/order/dto/OrderDTO.java
  src/main/java/com/infinityiterators/bookwms/order/mapper/OrderMapper.java
  src/main/java/com/infinityiterators/bookwms/order/model/service/OrderService.java
  src/main/java/com/infinityiterators/bookwms/order/view/OrderMainMenu.java
  src/main/java/com/infinityiterators/bookwms/order/view/PrintResult.java
  src/main/java/com/infinityiterators/bookwms/utils/database/MyBatisTemplate.java
  src/main/resources/order/mapper/OrderMapper.xml
Labels: enhancement

#51 db 템플릿 코드 수정 및 account 기반 mvc 모듈 배치
  build.gradle
  setup/Account.sql
  src/main/java/com/infinityiterators/bookwms/account/Account.java
  src/main/java/com/infinityiterators/bookwms/account/AccountController.java
  src/main/java/com/infinityiterators/bookwms/account/AccountMapper.java
  src/main/java/com/infinityiterators/bookwms/account/AccountService.java
  src/main/java/com/infinityiterators/bookwms/account/EncryptionEngine.java
  src/main/java/com/infinityiterators/bookwms/account/User.java
  src/main/java/com/infinityiterators/bookwms/account/view/MyPageView.java
  src/main/java/com/infinityiterators/bookwms/utils/database/MyBatisTemplate.java
  src/main/resources/com/infinityiterators/bookwms/account/AccountMapper.xml
  src/main/resources/config/mybatis-config.xml
  src/test/java/com/infinityiterators/bookwms/utils/database/TemplateTest.java
Labels: bug, enhancement, Account, hotfix

#47 feat: Add order completion and receipt printing functionality with main menu return
  src/main/java/com/infinityiterators/bookwms/order/controller/OrderController.java
  src/main/java/com/infinityiterators/bookwms/order/dao/OrderDAO.java
  src/main/java/com/infinityiterators/bookwms/order/mapper/OrderMapper.java
  src/main/java/com/infinityiterators/bookwms/order/model/service/OrderService.java
  src/main/java/com/infinityiterators/bookwms/order/view/OrderMainMenu.java
  src/main/resources/config/connection-info.properties
Labels: enhancement, Feature, Priority: High

#66 #20 출고내역 조회입니다
  src/main/java/com/infinityiterators/bookwms/shipment/controller/PrintResult.java
  src/main/java/com/infinityiterators/bookwms/shipment/controller/ShipmentController.java
  src/main/java/com/infinityiterators/bookwms/shipment/mapper/ShipmentMapper.java
  src/main/java/com/infinityiterators/bookwms/shipment/service/ShipmentService.java
  src/main/java/com/infinityiterators/bookwms/shipment/view/ShipmentView.java
  src/main/resources/com/infinityiterators/bookwms/shipment/mapper/ShipmentMapper.xml
Labels: hotfix

#69 입출고 파트 코드 병합
  src/main/java/com/infinityiterators/bookwms/receipt/Controller/ReceiptController.java
  src/main/java/com/infinityiterators/bookwms/receipt/view/ReceiptView.java
  src/main/java/com/infinityiterators/bookwms/shipment/view/ShipmentView.java
Labels: hotfix

#73 품절처리 dto 추가입니다
  src/main/java/com/infinityiterators/bookwms/receipt/model/dto/StockDTO.java
  src/main/resources/com/infinityiterators/bookwms/receipt/mapper/ReceiptMapper.xml
  src/main/resources/com/infinityiterators/bookwms/shipment/mapper/ShipmentMapper.xml
Labels: hotfix

#76 Merge cancelOrder module and refactor codebase
  src/main/java/com/infinityiterators/bookwms/cancelOrder/controller/CancelController.java
  src/main/java/com/infinityiterators/bookwms/cancelOrder/mapper/CancelMapper.java
  src/main/java/com/infinityiterators/bookwms/cancelOrder/model/dto/OrderDTO.java
  src/main/java/com/infinityiterators/bookwms/cancelOrder/service/CancelService.java
  src/main/java/com/infinityiterators/bookwms/cancelOrder/view/CancelView.java
  src/main/java/com/infinityiterators/bookwms/cancelOrder/view/PrintResult.java
  src/main/java/com/infinityiterators/bookwms/order/mapper/OrderMapper.java
  src/main/java/com/infinityiterators/bookwms/order/view/OrderMainMenu.java
  src/main/resources/com/infinityiterators/bookwms/cancelOrder/mapper/CancelMapper.xml
  src/main/resources/config/mybatis-config.xml
Labels: enhancement, Feature, Refactor, hotfix, merge

#79 #30 refactor: refatoring DTO
  src/main/java/com/infinityiterators/bookwms/receipt/model/dto/InRecordDTO.java
  src/main/java/com/infinityiterators/bookwms/receipt/view/ReceiptView.java
  src/main/java/com/infinityiterators/bookwms/shipment/view/ShipmentView.java
  src/main/resources/com/infinityiterators/bookwms/receipt/mapper/ReceiptMapper.xml
Labels: hotfix
